### ISSUE TITLE
train

### ISSUE THREAD

**Issue by sunwarm2001** [cschenxiang/DCD-GAN#1]
Hello!
Thanks for open source your code.
But when I was training, I noticed that the "option" folder was missing, are the training/testing parameters in the file the same as DCLGAN?Or could you send me the folder , if it is convenient?
Thanks for your help.

**Comment by cschenxiang** [comment]
Hello！You can use the "option" folder the same as DCLGAN for training. It is recommended to fine-tune the parameters.
