### ISSUE TITLE
Not options file

### ISSUE THREAD

**Issue by hlinqiao** [cschenxiang/DCD-GAN#3]
您好，非常感谢您，能在您的论文里学习到您的成果，也非常感谢您提供代码，只是我在跑您的代码时有些文件没有，像option、create_model等，能麻烦您提供一个完整的源代码给我吗？希望能发到我邮箱，55083401@QQ.com，非常感谢。

**Comment by cschenxiang** [comment]
> 您好，非常感谢您，能在您的论文里学习到您的成果，也非常感谢您提供代码，只是我在跑您的代码时有些文件没有，像option、create_model等，能麻烦您提供一个完整的源代码给我吗？希望能发到我邮箱，[55083401@QQ.com](mailto:55083401@QQ.com)，非常感谢。

The code has been updated.
